
INSERT INTO sensors (sensor_id, sensor_name) VALUES(1, "sensor1");
INSERT INTO sensors (sensor_id, sensor_name) VALUES(2, "sensor2");
INSERT INTO sensors (sensor_id, sensor_name) VALUES(3, "sensor3");
INSERT INTO sensors (sensor_id, sensor_name) VALUES(4, "sensor4");
INSERT INTO sensors (sensor_id, sensor_name) VALUES(5, "sensor5"); 

INSERT INTO sensor_data (sensor_id,value) VALUES (1,1);
INSERT INTO sensor_data (sensor_id,value) VALUES (1,10);
INSERT INTO sensor_data (sensor_id,value) VALUES (1,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (1,15);
INSERT INTO sensor_data (sensor_id,value) VALUES (1,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (1,25);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,1);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,10);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,15);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (2,25);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,1);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,10);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,15);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (3,25);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,1);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,10);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,15);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (4,25);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,1);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,10);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,15);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,20);
INSERT INTO sensor_data (sensor_id,value) VALUES (5,25);